name: HoYoLab

on:
  schedule:
    - cron: "55 */6 * * *"
  workflow_dispatch:

concurrency:
  group: hoyolab-auto
  cancel-in-progress: false

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: npm

      - run: npm install

      - name: Inject Cookie
        run: sed -i "s@__COOKIE__@${{ secrets.COOKIE }}@g" config.json5

      - name: Set timezone
        run: sudo timedatectl set-timezone Asia/Shanghai

      - run: npm start
