name: HoYoLab Daily

on:
  schedule:
    - cron: "5 4 * * *"
  workflow_dispatch:

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: 22

      - run: npm install

      - name: Inject cookie
        run: |
          sed -i "s|__COOKIE__|${{ secrets.COOKIE }}|g" config.json5

      - run: npm start
